### PR TITLE
Refactor feedstock dir into repos

### PR DESCRIPTION
**Pull request by jbusecke**
I finished refactoring the feedstock directory into separate feedstock repos. I have for now left climsim out since it is so big (need to confer with the authors on some things).

### CODE REVIEW

**Comment by jbusecke** [comment]
pre-commit.ci autofix

**Comment by jbusecke** [comment]
@andersy005 I just changed an error in the link to the meta.yaml of the metaflux_feedstock [here](https://github.com/leap-stc/metaflux_feedstock/blob/067530d56a98eff045e38684dce0bce4b422b4b4/feedstock/catalog.yaml#L2). What is the best way for me to retrigger a build here?

**Comment by jbusecke** [comment]
On a side note, until https://github.com/leap-stc/LEAP_template_feedstock/issues/28 is realized it might be likely that this sort of issue (forgetting to switch the repo url from the template) happens. Do you have any suggestion how to check for these? Should I insert some placeholder that will actually break things?

**Comment by andersy005** [comment]
> @andersy005 I just changed an error in the link to the meta.yaml of the metaflux_feedstock [here](https://github.com/leap-stc/metaflux_feedstock/blob/067530d56a98eff045e38684dce0bce4b422b4b4/feedstock/catalog.yaml#L2). What is the best way for me to retrigger a build here?

for changes that you want to be reflected in a pull request, one option is to add an empty commit:

```bash
git commit --allow-empty -m "Retrigger CI"
```

how does this sound? 

i also just added  `workflow_dispatch` trigger to the CI for when we want to manually re-build the catalog. this only applies to changes already on main/staging branches

**Comment by andersy005** [comment]
@jbusecke, you have a type in `https://github.com/leap-stc/metaflux_feedstock/blob/067530d56a98eff045e38684dce0bce4b422b4b4/feedstock/catalog.yaml#L2`. this should be `https://github.com/leap-stc/metaflux_feedstock/blob/main/feedstock/meta.yaml` (you are missing an `a` in meta)

**Comment by jbusecke** [comment]
Superseeded by #96

**Pull request closed without merging**
