### PR TITLE
Trying to debug daily metaflux recipe

### PR DESCRIPTION
**Pull request by jbusecke**
The daily metaflux recipe has been running for 3!!! days (cc @cisaacstern).  Testing if this is related to e.g. only some of the files here.

### CODE REVIEW

**Comment by jbusecke** [comment]
Up till 2012 went really fast

**Comment by jbusecke** [comment]
2018-2022 also went through in a reasonable time...maybe there is something wrong with one of the files from 2012-2018?

**Comment by jbusecke** [comment]
Or it is an issue when there are too many files in the recipe. Testing 2012-2018 now to figure that out.

**Comment by jbusecke** [comment]
I am leaning towards the fact that too many files somehow affect the outcome of this. I believe I have tested all files in different chunks at this point, and in smaller batches, they all went through.

**Comment by jbusecke** [comment]
2012-end worked well, going back on the start in increments now.

**Comment by cisaacstern** [comment]
@jbusecke anything I can do to help here?

**Comment by jbusecke** [comment]
I am not quite sure what the pickoff point here was, but all work on this dataset has been moved to https://github.com/leap-stc/metaflux_feedstock

**Pull request closed without merging**
