### PR TITLE
adding Jerry's notebook for troubleshooting

### PR DESCRIPTION
**Pull request by jerrylin96**
Notebook I added shows errors in the rest of the notebook I have. Thankfully, importing is no longer an issue, although I noticed that I have to explicitly import zarr and dask.

### CODE REVIEW

**Comment by jbusecke** [comment]
@andersy005 do you have any insight why pre-commit is not autofixing things automatically?

**Comment by jbusecke** [comment]
Hi @jerrylin96 sorry for the delay here. I see that you submitted two notebooks? Was that intended?

**Comment by jbusecke** [comment]
The [`xarray_to_zarr_jerry`](https://app.reviewnb.com/leap-stc/data-management/pull/1/) seems to have a bunch of errors. Was this from a test run?

**Comment by andersy005** [comment]
> @andersy005 do you have any insight why pre-commit is not autofixing things automatically?

i have currently disabled this feature, but i don't have a strong opinion on enabling it.

https://github.com/leap-stc/data-management/blob/a5d74870f30041a2b8e438545f4d72f7ba1b8b49/.pre-commit-config.yaml#L3

**Pull request merged**
