### PR TITLE
Add CM2-O feedstock

### PR DESCRIPTION
**Pull request by jbusecke**
@andersy005 if you could merge this asap, that would help me keep my demo at the site visit tomorrow more coherent.

### CODE REVIEW

**Comment by andersy005** [comment]
@jbusecke, i'm going to merge this shortly. however, it might not work in the data viewer because it appears this dataset uses the `scale_factor` and `offset` feature to store the data. the data viewer doesn't have support for the `mask_and_scale`(https://docs.xarray.dev/en/stable/generated/xarray.decode_cf.html#xarray.decode_cf)

**Comment by jbusecke** [comment]
Got it. That would be a pretty important feature to support? Or would this be sidestepped by the pyramids?

**Comment by andersy005** [comment]
>  Or would this be sidestepped by the pyramids?

unfortunately no. i just ran a quick smoke test to confirm this

Screenshot 2024-05-23 at 10 24 53
Screenshot 2024-05-23 at 10 25 00

**Comment by jbusecke** [comment]
eek!

**Pull request merged**
