### PR TITLE
Add Google ARCO ERA5 data

### PR DESCRIPTION
**Pull request by jbusecke**

### CODE REVIEW

**Comment by jbusecke** [comment]
I just got [this](https://github.com/leap-stc/data-management/actions/runs/9684813307/job/26723438935?pr=132#step:3:189) error and am a bit confused by it. I assume it has something to do with the fact that I removed the recipe object in meta.yaml [here](https://github.com/leap-stc/arco-era5_feedstock/blob/ae3816677dd838a4a0c170e106f3950ca089f6ad/feedstock/meta.yaml#L5-L6) (this is supposed to simply link an existing arco dataset. 

Secondly could we have caught this on the repo CI checks @andersy005? Could you explain what is different between 'validate-and-generate' and 'validate' which [ran successfully](https://github.com/leap-stc/arco-era5_feedstock/actions/runs/9684679545/job/26723023498) on the feedstock?

**Comment by norlandrhagen** [comment]
I think this lint PR https://github.com/leap-stc/arco-era5_feedstock/pull/3 to the yaml should fix the catalog validation error.

**Comment by norlandrhagen** [comment]
I think this should be G2G @jbusecke

**Comment by andersy005** [comment]
> Secondly could we have caught this on the repo CI checks @andersy005? Could you explain what is different between 'validate-and-generate' and 'validate' which [ran successfully](https://github.com/leap-stc/arco-era5_feedstock/actions/runs/9684679545/job/26723023498) on the feedstock?


i just checked, and there are some small differences in the [validation script ](https://github.com/leap-stc/leap-data-management-utils/blob/129e7c66315d25e9e01a4c8110465d3151a71998/leap_data_management_utils/catalog.py#L229)when validating a single feedstock (which is what happens in `validate`) versus a list of feedstocks (in `validate-and-generate`). i can look into merging both approaches in a consistent manner at  a latter time.

**Pull request merged**
