### PR TITLE
WIP: Add LLC 3D region data

### PR DESCRIPTION
**Pull request by jbusecke**
@dhruvbalwada starting the catalog page here. If you have time it would be great if you could check the preview. 

~~Marking this as WIP because that bucket is currently not public (requested a change already).~~

### CODE REVIEW

**Comment by jbusecke** [comment]
pre-commit.ci autofix

**Comment by jbusecke** [comment]
@andersy005 It seems like the final deployment (for previewing is not working here). Any chance you could take a look?

**Comment by andersy005** [comment]
> @andersy005 It seems like the final deployment (for previewing is not working here). Any chance you could take a look?

@jbusecke, this is a bug and i was able to track it down and fixed it as part of 

- https://github.com/carbonplan/leap-data-catalog/pull/82


in the meantime, you can use [this preview link](https://leap-data-catalog-git-feedstock-page-carbonplan.vercel.app/?catalog=https%3A%2F%2Fraw.githubusercontent.com%2Fleap-stc%2Fdata-management%2Fllc3d%2Fcatalog%2Foutput%2Fconsolidated-web-catalog.json)

**Comment by jbusecke** [comment]
Thanks @andersy005! Ill wait for https://github.com/leap-stc/LLC4320_12h_3D-regions_feedstock/issues/1 until moving ahead here!

**Comment by jbusecke** [comment]
@andersy005 I think this is ready to go. Should we wait for the preview or just go ahead and merge?

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Pull request merged**
